### ISSUE TITLE
Style Qs

### ISSUE THREAD

**Issue by StrykeSlammerII** [EMBTonkin/DAL9001#3]
OK, this one is purely a coding-style thing ^^

Your code uses this style for brackets:

```
public class Bob{
    public void someFunction(){
        // some code
    }
}
```

whereas I can't find the starting brackets with that style, so I'm used to doing

```
public class Bob
{
    public void someFunction()
    {
        // some code
    }
}
```

I can probably keep myself from just 'fixing' this on all the code I don't touch, but is it going to be a problem for you if my code has the extra whitespace?

**Comment by EMBTonkin** [comment]
I personally don't mind the style.  If it bugs you tones you can fix it.  About finding matching brackets, I think even the most simple of text editors will do bracket highlighting.

**Comment by StrykeSlammerII** [comment]
Yeah, I can use bracket highlighting if I need to find one... it's just less intuitive to me.
This'll be one way to see who did what work, maybe?  lol
