### ISSUE TITLE
commits

### ISSUE THREAD

**Issue by StrykeSlammerII** [EMBTonkin/DAL9001#4]
Ok this looks weird on my end:

I did a `git commit` to the master branch, it said it updated the repositories (and now insists my local code is up-to-date), but I'm not seeing my changes on the website.

I can grab files from command-line, is there some additional configuration I have to do to submit changes?  -confused-

I'll try to take a closer look tomorrow, but for now assume that DragonTree.addDragon( Dragon ), and blank/empty constructors for DragonTree and Dragon are all added if you don't get them somehow.

**Comment by EMBTonkin** [comment]
This is the part of Git I have never done.  I've only ever had one branch.  :/ 
Here's what I think is happening: you updated YOUR master branch.  You forked the repository so you have your own version, and you committed to that.  So what I think happens now is for the code to be merged, you submit a pull request on the main branch, I say yes, and then the two branches become one.  

If that's not what you think is happening I'll do some google work.

**Comment by StrykeSlammerII** [comment]
I'll have to doublecheck, but I did remove the one fork I made on the site, and the branch I was trying to make earlier never showed up on-site. Right now I've just been working on the master branch on my side of things, but I was able to pull/merge/whatever-command-it-is your last set of changes just fine. I thought that meant I was still in your repository, but who knows? XD

I'm gonna have to go through github's Git Flow documentation and see if that explains anything better for me ...

**Comment by EMBTonkin** [comment]
I meant to look into this (and do other things) tonight but something came up and I had no time.  If you don't figure it out before I certainly will try tomorrow since this is important.  No point in coding things if we can't get them to eachother.

**Comment by StrykeSlammerII** [comment]
Worst case is I just have to drop them in via the website though, right? I'll edit this later if I find a solution tonight :)

...ok apparently I didn't know the right command to use.  'git push' is what sends commits back to the repository; I'm not sure yet why 'git commit' is different from 'git push', but it's just part of my learning curve here.

Important part # 2: EITHER 1) you can [add me as a Collaborator](https://help.github.com/articles/adding-collaborators-to-a-personal-repository/)  OR 2) I'm forced to fork and send pull requests.
I guess it depends what type of [collaboration model](https://help.github.com/articles/types-of-collaborative-development-models) you want.

Once we get going we'll probably have more branches and pull requests on those, but I don't _think_ that'll be essential until we have a working product ;)

**Comment by EMBTonkin** [comment]
Oh, I see you edited your comment. (I don't get notifications about that).
I was just about to say I had added you as a Collaborator, so you now should be able to push to the master directory!

The difference between 'commit' and 'push,' as I understand it:
Committing is saying 'I have these changes, and they should all go together.'  Maybe you fixed something, or added a new feature.  Pushing is taking all the changes you have and putting them in the master repository.  I think style says that commits should be organized.  Don't commit stuff that does not work, and put separate features in separate commits.  This way, if something goes wrong, you know which commit to undo.  Also, when committing, be sure to fill out the commit form.  The first line should be a short descriptive title, and the rest should be longer paragraph style discretion of what has changed.  

Now you can add your code and we can really get cooking!  Yay!  :D

**Comment by StrykeSlammerII** [comment]
Yay it works!
Not sure where that "merge branch 'master' thing came from, but at least you can see I'm adding stuff now ^^

Closing this issue as resolved :D
